/* Generated by cbindgen — do not edit */

#ifndef AWALTERMINAL_H
#define AWALTERMINAL_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a terminal surface.
 */
typedef struct ATSurface ATSurface;

/**
 * C-compatible cell for FFI transfer.
 */
typedef struct CCell {
    uint32_t codepoint;
    uint8_t fg_r;
    uint8_t fg_g;
    uint8_t fg_b;
    uint8_t fg_a;
    uint8_t bg_r;
    uint8_t bg_g;
    uint8_t bg_b;
    uint8_t bg_a;
    uint16_t attrs;
} CCell;

/**
 * Create a new terminal surface with the given dimensions.
 */
struct ATSurface *at_surface_new(uint32_t cols,
                                 uint32_t rows);

/**
 * Destroy a terminal surface.
 */
void at_surface_destroy(struct ATSurface *surface);

/**
 * Spawn a shell process. Returns 0 on success, -1 on failure.
 */
int32_t at_surface_spawn_shell(struct ATSurface *surface,
                               const char *shell);

/**
 * Spawn a shell running a specific command. Returns 0 on success, -1 on failure.
 * The shell is invoked as a login shell with `-c command`.
 */
int32_t at_surface_spawn_command(struct ATSurface *surface,
                                 const char *shell,
                                 const char *command);

/**
 * Get the PTY master file descriptor (for polling).
 */
int at_surface_get_fd(const struct ATSurface *surface);

/**
 * Get the child shell PID.
 */
int32_t at_surface_get_child_pid(const struct ATSurface *surface);

/**
 * Read from the PTY and process VT sequences. Returns number of bytes read, 0 if nothing available, -1 on error.
 */
int32_t at_surface_process_pty(struct ATSurface *surface);

/**
 * Send a key event (raw bytes) to the PTY.
 */
int32_t at_surface_key_event(struct ATSurface *surface,
                             const uint8_t *data,
                             uint32_t len);

/**
 * Get the screen dimensions.
 */
void at_surface_get_size(const struct ATSurface *surface,
                         uint32_t *cols,
                         uint32_t *rows);

/**
 * Resize the terminal surface.
 */
void at_surface_resize(struct ATSurface *surface,
                       uint32_t cols,
                       uint32_t rows);

/**
 * Read cells from the screen into the provided buffer.
 * Buffer must have space for (cols * rows) CCells.
 * Returns the number of cells written.
 */
uint32_t at_surface_read_cells(const struct ATSurface *surface,
                               struct CCell *out,
                               uint32_t max_cells);

/**
 * Get cursor position.
 */
void at_surface_get_cursor(const struct ATSurface *surface,
                           uint32_t *row,
                           uint32_t *col,
                           bool *visible);

/**
 * Check if screen content has changed since last check. Resets the dirty flag.
 */
bool at_surface_is_dirty(struct ATSurface *surface);

/**
 * Feed raw bytes directly into the VT parser (no PTY needed).
 * Used for rendering TUI menus before a shell is spawned.
 */
void at_surface_feed_bytes(struct ATSurface *surface,
                           const uint8_t *data,
                           uint32_t len);

/**
 * Initialize logging (call once at startup).
 */
void at_init_logging(void);

#endif  /* AWALTERMINAL_H */
