/* Generated by cbindgen — do not edit */

#ifndef CLAUDETERMINAL_H
#define CLAUDETERMINAL_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a terminal surface.
 */
typedef struct CTSurface CTSurface;

/**
 * C-compatible cell for FFI transfer.
 */
typedef struct CCell {
    uint32_t codepoint;
    uint8_t fg_r;
    uint8_t fg_g;
    uint8_t fg_b;
    uint8_t fg_a;
    uint8_t bg_r;
    uint8_t bg_g;
    uint8_t bg_b;
    uint8_t bg_a;
    uint16_t attrs;
} CCell;

/**
 * Create a new terminal surface with the given dimensions.
 */
struct CTSurface *ct_surface_new(uint32_t cols,
                                 uint32_t rows);

/**
 * Destroy a terminal surface.
 */
void ct_surface_destroy(struct CTSurface *surface);

/**
 * Spawn a shell process. Returns 0 on success, -1 on failure.
 */
int32_t ct_surface_spawn_shell(struct CTSurface *surface,
                               const char *shell);

/**
 * Get the PTY master file descriptor (for polling).
 */
int ct_surface_get_fd(const struct CTSurface *surface);

/**
 * Read from the PTY and process VT sequences. Returns number of bytes read, 0 if nothing available, -1 on error.
 */
int32_t ct_surface_process_pty(struct CTSurface *surface);

/**
 * Send a key event (raw bytes) to the PTY.
 */
int32_t ct_surface_key_event(struct CTSurface *surface,
                             const uint8_t *data,
                             uint32_t len);

/**
 * Get the screen dimensions.
 */
void ct_surface_get_size(const struct CTSurface *surface,
                         uint32_t *cols,
                         uint32_t *rows);

/**
 * Resize the terminal surface.
 */
void ct_surface_resize(struct CTSurface *surface,
                       uint32_t cols,
                       uint32_t rows);

/**
 * Read cells from the screen into the provided buffer.
 * Buffer must have space for (cols * rows) CCells.
 * Returns the number of cells written.
 */
uint32_t ct_surface_read_cells(const struct CTSurface *surface,
                               struct CCell *out,
                               uint32_t max_cells);

/**
 * Get cursor position.
 */
void ct_surface_get_cursor(const struct CTSurface *surface,
                           uint32_t *row,
                           uint32_t *col,
                           bool *visible);

/**
 * Check if screen content has changed since last check. Resets the dirty flag.
 */
bool ct_surface_is_dirty(struct CTSurface *surface);

/**
 * Initialize logging (call once at startup).
 */
void ct_init_logging(void);

#endif  /* CLAUDETERMINAL_H */
